ValueSet: LaboratoryTests
Id: laboratory-tests
Title: "Laboratory Tests"
Description: "Laboratory tests in the context of NAPKON Pediatrics Module"
* $loinc#42908-4 "Hematocrit [Volume Fraction] of Capillary blood"
* $loinc#41654-5 "Hematocrit [Volume Fraction] of Venous blood"
* $loinc#32354-3 "Hematocrit [Volume Fraction] of Arterial blood"
* $loinc#17809-5 "Hematocrit [Volume Fraction] of Urine"
* $loinc#20570-8 "Hematocrit [Volume Fraction] of Blood"
* $loinc#5894-1 "Prothrombin time (PT) actual/Normal"
* $loinc#2951-2 "Sodium [Moles/volume] in Serum or Plasma"
* $loinc#39791-9 "Sodium [Moles/volume] in Venous blood"
* $loinc#32717-1 "Sodium [Moles/volume] in Arterial blood"
* $loinc#2947-0 "Sodium [Moles/volume] in Blood"
* $loinc#2955-3 "Sodium [Moles/volume] in Urine"
* $loinc#72903-8 "Urea [Moles/volume] in Blood"
* $loinc#22700-9 "Urea [Moles/volume] in Urine"
* $loinc#20977-5 "Urea [Mass/volume] in Blood"
* $loinc#3092-4 "Urea [Mass/volume] in Urine"
* $loinc#76630-3 "Amylase [Enzymatic activity/volume] in Blood"
* $loinc#1798-8 "Amylase [Enzymatic activity/volume] in Serum or Plasma"
* $loinc#14389-1 "Amylase [Enzymatic activity/volume] in Cerebral spinal fluid"
* $loinc#1795-4 "Amylase [Enzymatic activity/volume] in Body fluid"
* $loinc#70218-3 "Triglyceride [Moles/volume] in Blood"
* $loinc#59572-8 "Triglyceride [Moles/volume] in Urine"
* $loinc#3043-7 "Triglyceride [Mass/volume] in Blood"
* $loinc#14450-1 "Triglyceride [Mass/volume] in Urine"
* $loinc#1746-7 "Albumin [Mass/volume] in Cerebral spinal fluid"
* $loinc#1754-1 "Albumin [Mass/volume] in Urine"
* $loinc#1751-7 "Albumin [Mass/volume] in Serum or Plasma"
* $loinc#1747-5 "Albumin [Mass/volume] in Body fluid"
* $loinc#54347-0 "Albumin [Moles/volume] in Serum or Plasma"
* $loinc#76480-3 "Albumin [Moles/volume] in Cerebral spinal fluid"
* $loinc#76625-3 "Alanine aminotransferase [Enzymatic activity/volume] in Blood"
* $loinc#1742-6 "Alanine aminotransferase [Enzymatic activity/volume] in Serum or Plasma"
* $loinc#25302-1 "Alanine aminotransferase [Enzymatic activity/volume] in Body fluid"
* $loinc#3040-3 "Lipase [Enzymatic activity/volume] in Serum or Plasma"
* $loinc#10888-6 "Lipase [Enzymatic activity/volume] in Urine"
* $loinc#15212-4 "Lipase [Enzymatic activity/volume] in Body fluid"
* $loinc#2151-9 "Creatine kinase [Enzymatic activity/volume] in Cerebral spinal fluid"
* $loinc#2157-6 "Creatine kinase [Enzymatic activity/volume] in Serum or Plasma"
* $loinc#16688-4 "Creatine kinase [Enzymatic activity/volume] in Body fluid"
* $loinc#32673-6 "Creatine kinase.MB [Enzymatic activity/volume] in Serum or Plasma"
* $loinc#51506-4 "Creatine kinase.MB [Enzymatic activity/volume] in Cerebral spinal fluid by Electrophoresis"
* $loinc#2154-3 "Creatine kinase.MB [Enzymatic activity/volume] in Serum or Plasma by Electrophoresis"
* $loinc#30341-2 "Erythrocyte sedimentation rate"
* $loinc#26848-2 "Interleukin 10 [Mass/volume] in Serum or Plasma"
* $loinc#49733-9 "Interleukin 10 [Mass/volume] in Body fluid"
* $loinc#49909-5 "Interleukin 10 [Mass/volume] in Cerebral spinal fluid"
* $loinc#76039-7 "Interleukin 2 Receptor Soluble [Mass/volume] in Serum or Plasma"
* $loinc#33415-1 "IgG [Mass/volume] in Urine"
* $loinc#2465-3 "IgG [Mass/volume] in Serum or Plasma"
* $loinc#15183-7 "IgG [Mass/volume] in Body fluid"
* $loinc#2464-6 "IgG [Mass/volume] in Cerebral spinal fluid"
* $loinc#76490-2 "IgG [Moles/volume] in Urine"
* $loinc#77177-4 "IgG [Moles/volume] in Serum or Plasma"
* $loinc#76489-4 "IgG [Moles/volume] in Cerebral spinal fluid"
* $loinc#6801-5 "Complement C3 [Mass/volume] in Body fluid"
* $loinc#4485-9 "Complement C3 [Mass/volume] in Serum or Plasma"
* $loinc#6908-8 "Complement C4 [Mass/volume] in Body fluid"
* $loinc#4498-2 "Complement C4 [Mass/volume] in Serum or Plasma"
* $loinc#14607-6 "Nuclear Ab [Presence] in Body fluid"
* $loinc#8061-4 "Nuclear Ab [Presence] in Serum"
* $loinc#17351-8 "Neutrophil cytoplasmic Ab [Presence] in Serum"
* $loinc#34439-0 "Natural killer cell function [Units/volume] in Blood"
* $loinc#26454-9 "Erythrocytes [#/volume] in Cerebral spinal fluid"
* $loinc#26465-5 "Leukocytes [#/volume] in Cerebral spinal fluid"
* $loinc#58470-6 "Nucleated cells [#/volume] in Cerebral spinal fluid"
* $loinc#35034-8 "Mesothelial cells [#/volume] in Cerebral spinal fluid"
* $loinc#2880-3 "Protein [Mass/volume] in Cerebral spinal fluid"
* $loinc#2342-4 "Glucose [Mass/volume] in Cerebral spinal fluid"
* $loinc#14744-7 "Glucose [Moles/volume] in Cerebral spinal fluid"
* $loinc#27941-4 "Lactate [Mass/volume] in Cerebral spinal fluid"
* $loinc#2520-5 "Lactate [Moles/volume] in Cerebral spinal fluid"
* $loinc#82874-9 "Calprotectin [Mass/volume] in Stool"
* $loinc#93771-4 "Calprotectin [Mass/volume] in Synovial fluid"
